sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli4.2

script:
  - ng build --prod --aot
  - ng test